# Generated by Django 4.1.5 on 2023-01-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sr_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_location', models.CharField(max_length=50)),
                ('shop_id', models.IntegerField()),
                ('shop_email', models.EmailField(max_length=254)),
                ('shop_phone', models.IntegerField()),
                ('shop_password', models.CharField(max_length=50)),
                ('shop_c_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ur_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField()),
                ('user_location', models.CharField(max_length=50)),
                ('user_pincode', models.IntegerField()),
                ('user_password', models.CharField(max_length=50)),
                ('user_c_password', models.CharField(max_length=50)),
            ],
        ),
    ]
