# Generated by Django 4.1.5 on 2023-02-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_iu_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ur_model',
        ),
    ]
