# Generated by Django 4.1.5 on 2023-02-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart_model',
        ),
    ]
