# Generated by Django 4.1.5 on 2023-02-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0008_buy"),
    ]

    operations = [
        migrations.RenameModel(old_name="buy", new_name="buy_model",),
    ]
