# Generated by Django 4.1.5 on 2023-02-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0009_rename_buy_buy_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="buy_model", name="product_description",),
        migrations.RemoveField(model_name="buy_model", name="product_image",),
    ]
