# Generated by Django 4.1.5 on 2023-02-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0010_remove_buy_model_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="card_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_holder_name", models.CharField(max_length=50)),
                ("card_number", models.IntegerField()),
                ("address", models.CharField(max_length=50)),
                ("phone", models.IntegerField()),
                ("date", models.CharField(max_length=50)),
                ("security_code", models.IntegerField()),
            ],
        ),
    ]
