# Generated by Django 4.1.5 on 2023-02-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0011_card_model"),
    ]

    operations = [
        migrations.RemoveField(model_name="card_model", name="address",),
        migrations.RemoveField(model_name="card_model", name="phone",),
    ]
