# Generated by Django 4.1.5 on 2023-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0013_iu_model_shop_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart_model",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishlist_model",
            name="user_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
