# Generated by Django 4.1.5 on 2023-02-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0014_cart_model_user_id_wishlist_model_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="sn_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="un_models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
