# Generated by Django 4.1.5 on 2023-02-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0015_sn_models_un_models"),
    ]

    operations = [
        migrations.RenameModel(old_name="sn_models", new_name="sn_model",),
        migrations.RenameModel(old_name="un_models", new_name="un_model",),
    ]
