# Generated by Django 4.1.5 on 2023-02-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0016_rename_sn_models_sn_model_rename_un_models_un_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sn_model",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="un_model",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
